version: '3.0'
services:
  cloud:
    image: helium:matmul4-dec
    build: 
      context: ./../../../..
      dockerfile: Dockerfile
      args:
        - APP=./deployment/scenarios/matmul4-dec/node
    command: -expDuration 10s
    container_name: cloud
    ports:
      - "40000:40000"
    volumes:
      - ../cloud.json:/helium/config/node.json
      - ./nodelist.json:/helium/config/nodelist.json
    profiles: ["all", "cloud"]
      

  node-0:
    image: helium:matmul4-dec
    build: 
      context: ./../../../..
      dockerfile: Dockerfile
      args:
        - APP=./deployment/scenarios/matmul4-dec/node
    container_name: node-0
    entrypoint: /helium/shape_egress_and_start.sh
    env_file:
      - 'network.env'
    cap_add:
      - NET_ADMIN
    volumes:
      - ../node-0.json:/helium/config/node.json
      - ./nodelist.json:/helium/config/nodelist.json
    profiles: ["all", "clients"]
      

  node-1:
    image: helium:matmul4-dec
    build: 
      context: ./../../../..
      dockerfile: Dockerfile
      args:
        - APP=./deployment/scenarios/matmul4-dec/node
    container_name: node-1
    entrypoint: /helium/shape_egress_and_start.sh
    env_file:
      - 'network.env'
    cap_add:
      - NET_ADMIN
    volumes:
      - ../node-1.json:/helium/config/node.json
      - ./nodelist.json:/helium/config/nodelist.json
    profiles: ["all", "clients"]

  node-2:
    image: helium:matmul4-dec
    build: 
      context: ./../../../..
      dockerfile: Dockerfile
      args:
        - APP=./deployment/scenarios/matmul4-dec/node
    container_name: node-2
    entrypoint: /helium/shape_egress_and_start.sh
    env_file:
      - 'network.env'
    cap_add:
      - NET_ADMIN
    volumes:
      - ../node-2.json:/helium/config/node.json
      - ./nodelist.json:/helium/config/nodelist.json
    profiles: ["all", "clients"]

  node-3:
    image: helium:matmul4-dec
    build: 
      context: ./../../../..
      dockerfile: Dockerfile
      args:
        - APP=./deployment/scenarios/matmul4-dec/node
    container_name: node-3
    entrypoint: /helium/shape_egress_and_start.sh
    env_file:
      - 'network.env'
    cap_add:
      - NET_ADMIN
    volumes:
      - ../node-3.json:/helium/config/node.json
      - ./nodelist.json:/helium/config/nodelist.json
    profiles: ["all", "clients"]
# volumes:
  # cloud-data:
  # node-a-data: