version: '3.0'
services:
  cloud:
    image: heliummpc/helium:latest
    container_name: cloud
    command: -docompute=false
    volumes:
      - ../cloud.json:/helium/config/node.json
      - ../setup.json:/helium/config/setup.json
      - ../compute.json:/helium/config/compute.json
      - ./nodelist.json:/helium/config/nodelist.json
      # - cloud-data:/helium/data
    profiles: ["all", "cloud"]

  node-0:
    image: heliummpc/helium:latest
    container_name: node-0
    command: -docompute=false
    cap_add:
      - NET_ADMIN
    environment:
      - RATE_LIMIT=5mbit
    volumes:
      - ../node0.json:/helium/config/node.json
      - ../setup.json:/helium/config/setup.json
      - ../compute.json:/helium/config/compute.json
      - ./nodelist.json:/helium/config/nodelist.json

      # Persistent data across container reboots.
      # - node-a-data:/helium/data
    profiles: ["all", "clients"]

  node-1:
    image: heliummpc/helium:latest
    container_name: node-1
    command: -docompute=false
    cap_add:
      - NET_ADMIN
    environment:
      - RATE_LIMIT=5mbit
    volumes:
      - ../node1.json:/helium/config/node.json
      - ../setup.json:/helium/config/setup.json
      - ../compute.json:/helium/config/compute.json
      - ./nodelist.json:/helium/config/nodelist.json

      # No persistency.
    profiles: ["all", "clients"]

  node-2:
    image: heliummpc/helium:latest
    container_name: node-2
    command: -docompute=false
    cap_add:
      - NET_ADMIN
    environment:
      - RATE_LIMIT=5mbit
    volumes:
      - ../node2.json:/helium/config/node.json
      - ../setup.json:/helium/config/setup.json
      - ../compute.json:/helium/config/compute.json
      - ./nodelist.json:/helium/config/nodelist.json
    profiles: ["all", "clients"]

# volumes:
  # cloud-data:
  # node-a-data: