package protocols

import (
	"testing"

	"github.com/ChristianMct/helium"
	"github.com/ChristianMct/helium/heliumtest"
	"github.com/stretchr/testify/require"
	"github.com/tuneinsight/lattigo/v6/core/rlwe"
	mhe "github.com/tuneinsight/lattigo/v6/multiparty"
	"github.com/tuneinsight/lattigo/v6/ring"
)

// TestKeySwitchMasks checks that the masks of the key-switching shares cancel out when, and
// only when, they are generated by all the participants for the same protocol and ciphertext.
func TestKeySwitchMasks(t *testing.T) {
	hid := helium.NodeID("helper")
	testSess, err := heliumtest.NewSessions(4, 3, TestPN12QP109, hid)
	require.NoError(t, err)
	params := testSess.RlweParams
	ringQ := params.RingQ()

	sig := Signature{Type: DEC, Args: map[string]string{"target": "node-0", "smudging": "40"}}
	pd0 := Descriptor{Signature: sig, Participants: []helium.NodeID{"node-0", "node-1", "node-2"}, Aggregator: hid}
	pd1 := Descriptor{Signature: sig, Participants: []helium.NodeID{"node-0", "node-1", "node-3"}, Aggregator: hid}

	zeroKey := rlwe.NewSecretKey(params)
	in0 := &KeySwitchInput{OutputKey: zeroKey, InpuCt: testSess.Encryptor.EncryptZeroNew(params.MaxLevel())}
	in1 := &KeySwitchInput{OutputKey: zeroKey, InpuCt: testSess.Encryptor.EncryptZeroNew(params.MaxLevel())}

	// mask returns the mask of node nid for the protocol pd and input in
	mask := func(nid helium.NodeID, pd Descriptor, in Input) ring.Poly {
		p, err := NewProtocol(pd, testSess.Nodes[nid])
		require.NoError(t, err)
		m := ringQ.NewPoly()
		ctDigest, err := keySwitchInputDigest(in) // TODO: recomputes the digest if the same Protocol ran GenShare, could be cached.
		require.NoError(t, err)
		level := in.(*KeySwitchInput).InpuCt.Level()
		require.NoError(t, p.addKeySwitchMask(ctDigest, level, m))
		return m
	}
	sum := func(masks ...ring.Poly) ring.Poly {
		s := ringQ.NewPoly()
		for _, m := range masks {
			ringQ.Add(s, m, s)
		}
		return s
	}
	zero := ringQ.NewPoly()

	t.Run("SameSetAndCiphertext", func(t *testing.T) {
		for _, pd := range []Descriptor{pd0, pd1} {
			masks := make([]ring.Poly, 0, len(pd.Participants))
			for _, nid := range pd.Participants {
				m := mask(nid, pd, in0)
				require.False(t, m.Equal(&zero))
				require.True(t, m.Equal(ptr(mask(nid, pd, in0))), "masks should be deterministic")
				masks = append(masks, m)
			}
			require.True(t, sum(masks...).Equal(&zero))
			require.False(t, sum(masks[1:]...).Equal(&zero))
		}
	})

	t.Run("DifferentSets", func(t *testing.T) {
		require.False(t, mask("node-0", pd0, in0).Equal(ptr(mask("node-0", pd1, in0))))
		// node-0 and node-1 are in both sets
		require.False(t, sum(mask("node-0", pd0, in0), mask("node-1", pd0, in0), mask("node-3", pd1, in0)).Equal(&zero))
		require.False(t, sum(mask("node-0", pd1, in0), mask("node-1", pd0, in0), mask("node-2", pd0, in0)).Equal(&zero))
	})

	t.Run("DifferentCiphertexts", func(t *testing.T) {
		require.False(t, mask("node-0", pd0, in0).Equal(ptr(mask("node-0", pd0, in1))))
		require.False(t, sum(mask("node-0", pd0, in1), mask("node-1", pd0, in0), mask("node-2", pd0, in0)).Equal(&zero))
	})

	t.Run("DifferentSignatures", func(t *testing.T) {
		pd := pd0
		pd.Signature = Signature{Type: DEC, Args: map[string]string{"target": "node-1", "smudging": "40"}}
		require.False(t, mask("node-0", pd0, in0).Equal(ptr(mask("node-0", pd, in0))))
	})

	t.Run("SmudgingNoise", func(t *testing.T) {
		// the difference of the unmasked shares of a node for two ciphertexts must not be noiseless
		p, err := NewProtocol(pd0, testSess.Nodes["node-1"])
		require.NoError(t, err)
		sk, err := testSess.Nodes["node-1"].GetSecretKeyForGroup(pd0.Participants)
		require.NoError(t, err)
		noise := func(in *KeySwitchInput) ring.Poly {
			require.True(t, in.InpuCt.IsNTT)
			share := p.AllocateShare()
			require.NoError(t, p.GenShare(sk, in, &share))
			e := *share.MHEShare.(*mhe.KeySwitchShare).Value.CopyNew() // c1 * sk + e + mask
			ringQ.Sub(e, mask("node-1", pd0, in), e)
			c1sk := ringQ.NewPoly()
			ringQ.MulCoeffsMontgomery(in.InpuCt.Value[1], sk.Value.Q, c1sk)
			ringQ.Sub(e, c1sk, e)
			ringQ.INTT(e, e)
			require.Less(t, ringQ.Log2OfStandardDeviation(e), 10.0, "the share should be c1 * sk + e + mask")
			return e
		}
		e0, e1 := noise(in0), noise(in1)
		require.False(t, e0.Equal(&e1))
		require.True(t, e0.Equal(ptr(noise(in0))))
	})
}

func ptr[T any](v T) *T { return &v }
