---
- hosts: all
  become: true
  vars:
    # default_container_name: docker
    default_container_image: heliummpc/helium:latest

  tasks:

    - name: Pull default Docker image
      community.docker.docker_image:
        name: "{{ default_container_image }}"
        source: pull
        force_source: yes

    # - name: Create default containers
    #   community.docker.docker_container:
    #     name: "{{ default_container_name }}{{ item }}"
    #     image: "{{ default_container_image }}"
    #     command: "{{ default_container_command }}"
    #     state: present
    #   with_sequence: count={{ container_count }}