---
- hosts: localhost
  gather_facts: no
  vars_prompt:
  - name: scenario
    prompt: Enter the scenario folder name
    private: false
  vars:
    scenario_folder: "../scenarios/{{ scenario }}"
    nodelist_file: "{{ scenario_folder }}/remote/nodelist.json"
    nodelist: "{{ lookup('file', nodelist_file) }}"


  tasks:
    - name: Reading inventory from scenario nodelist
      add_host:
        hostname: "{{ item.NodeAddress.split(':')[0] }}"
        groups: scenario_hosts
        nodeid: "{{ item.NodeID }}"
        scenario_folder: "../scenarios/{{ scenario }}"
      with_items:  "{{ nodelist | to_json | from_json }}"

- hosts: scenario_hosts
  become: true
  tasks:
    - name: Create the /helium/config directory
      ansible.builtin.file:
        path: /helium/config
        state: directory
        mode: '0755'
    
    - name: Create the /helium/stats directory
      ansible.builtin.file:
        path: /helium/stats
        state: directory
        mode: '0755'

    - name: Copying node config file
      ansible.builtin.copy:
        src: "{{ scenario_folder }}/{{ nodeid }}.json"
        dest: /helium/config/node.json

    - name: Copying node list file
      ansible.builtin.copy:
        src: "{{ scenario_folder }}/remote/nodelist.json"
        dest: /helium/config/nodelist.json

    - name: Copying protocol map file
      ansible.builtin.copy:
        src: "{{ scenario_folder }}/protocolmap.json"
        dest: /helium/config/protocolmap.json

    - name: Starting containers
      community.docker.docker_container:
        name: helium
        image: heliummpc/helium:latest
        state: started
        restart: true
        ports:
          - "40000:40000"
        volumes:
          - /helium/config:/helium/config
          - /helium/stats:/helium/stats
      when: nodeid != "full-0"