version: '3.0'
services:
  cloud:
    image: heliummpc/helium:latest
    container_name: cloud
    command: -docompute -outputMetrics
    volumes:
      - ../cloud.json:/helium/config/node.json
      - ../setup.json:/helium/config/setup.json
      - ../compute.json:/helium/config/compute.json
      - ./nodelist.json:/helium/config/nodelist.json
      - /root/results:/helium/stats
    ports:
      - "40000:40000"
    profiles: ["all", "cloud"]

  node-0:
    image: heliummpc/helium:latest
    container_name: node-0
    command: -docompute -outputMetrics
    volumes:
      - ../node0.json:/helium/config/node.json
      - ../setup.json:/helium/config/setup.json
      - ../compute.json:/helium/config/compute.json
      - ./nodelist.json:/helium/config/nodelist.json
      # Persistent data across container reboots.
      - /root/results:/helium/stats
    profiles: ["all", "clients"]

  node-1:
    image: heliummpc/helium:latest
    container_name: node-1
    command: -docompute
    volumes:
      - ../node1.json:/helium/config/node.json
      - ../setup.json:/helium/config/setup.json
      - ../compute.json:/helium/config/compute.json
      - ./nodelist.json:/helium/config/nodelist.json

      # No persistency.
    profiles: ["all", "clients"]

  node-2:
    image: heliummpc/helium:latest
    container_name: node-2
    command: -docompute
    volumes:
      - ../node2.json:/helium/config/node.json
      - ../setup.json:/helium/config/setup.json
      - ../compute.json:/helium/config/compute.json
      - ./nodelist.json:/helium/config/nodelist.json
    profiles: ["all", "clients"]

  node-3:
    image: heliummpc/helium:latest
    container_name: node-3
    command: -docompute
    volumes:
      - ../node3.json:/helium/config/node.json
      - ../setup.json:/helium/config/setup.json
      - ../compute.json:/helium/config/compute.json
      - ./nodelist.json:/helium/config/nodelist.json

      # No persistency.
    profiles: ["all", "clients"]

  node-4:
    image: heliummpc/helium:latest
    container_name: node-4
    command: -docompute
    volumes:
      - ../node4.json:/helium/config/node.json
      - ../setup.json:/helium/config/setup.json
      - ../compute.json:/helium/config/compute.json
      - ./nodelist.json:/helium/config/nodelist.json
    profiles: ["all", "clients"]

  node-5:
    image: heliummpc/helium:latest
    container_name: node-5
    command: -docompute
    volumes:
      - ../node5.json:/helium/config/node.json
      - ../setup.json:/helium/config/setup.json
      - ../compute.json:/helium/config/compute.json
      - ./nodelist.json:/helium/config/nodelist.json

      # No persistency.
    profiles: ["all", "clients"]

  node-6:
    image: heliummpc/helium:latest
    container_name: node-6
    command: -docompute
    volumes:
      - ../node6.json:/helium/config/node.json
      - ../setup.json:/helium/config/setup.json
      - ../compute.json:/helium/config/compute.json
      - ./nodelist.json:/helium/config/nodelist.json
    profiles: ["all", "clients"]

  node-7:
    image: heliummpc/helium:latest
    container_name: node-7
    command: -docompute
    volumes:
      - ../node7.json:/helium/config/node.json
      - ../setup.json:/helium/config/setup.json
      - ../compute.json:/helium/config/compute.json
      - ./nodelist.json:/helium/config/nodelist.json

      # No persistency.
    profiles: ["all", "clients"]

  node-8:
    image: heliummpc/helium:latest
    container_name: node-8
    command: -docompute
    volumes:
      - ../node8.json:/helium/config/node.json
      - ../setup.json:/helium/config/setup.json
      - ../compute.json:/helium/config/compute.json
      - ./nodelist.json:/helium/config/nodelist.json
    profiles: ["all", "clients"]

# volumes:
#   cloud-data:
#   node-data: