version: '3.0'
services:
  cloud:
    image: heliummpc/helium:latest
    container_name: cloud
    command: -docompute
    volumes:
      - ../cloud.json:/helium/config/node.json
      - ../setup.json:/helium/config/setup.json
      - ../compute.json:/helium/config/compute.json
      - ./nodelist.json:/helium/config/nodelist.json

      # - cloud-data:/helium/data
    profiles: ["all", "cloud"]
    ports:
          - "40000:40000"

  node-0:
    image: heliummpc/helium:latest
    container_name: node-0
    command: -docompute
    volumes:
      - ../node-0.json:/helium/config/node.json
      - ../setup.json:/helium/config/setup.json
      - ../compute.json:/helium/config/compute.json
      - ./nodelist.json:/helium/config/nodelist.json

      # Persistent data across container reboots.
      # - node-a-data:/helium/data
    profiles: ["all", "clients"]

  node-1:
    image: heliummpc/helium:latest
    container_name: node-1
    command: -docompute
    volumes:
      - ../node-1.json:/helium/config/node.json
      - ../setup.json:/helium/config/setup.json
      - ../compute.json:/helium/config/compute.json
      - ./nodelist.json:/helium/config/nodelist.json

      # No persistency.
    profiles: ["all", "clients"]

  node-2:
    image: heliummpc/helium:latest
    container_name: node-2
    command: -docompute
    volumes:
      - ../node-2.json:/helium/config/node.json
      - ../setup.json:/helium/config/setup.json
      - ../compute.json:/helium/config/compute.json
      - ./nodelist.json:/helium/config/nodelist.json

      # No persistency.
    profiles: ["all", "clients"]

  node-3:
    image: heliummpc/helium:latest
    container_name: node-3
    command: -docompute
    volumes:
      - ../node-3.json:/helium/config/node.json
      - ../setup.json:/helium/config/setup.json
      - ../compute.json:/helium/config/compute.json
      - ./nodelist.json:/helium/config/nodelist.json

      # No persistency.
    profiles: ["all", "clients"]

  node-4:
    image: heliummpc/helium:latest
    container_name: node-4
    command: -docompute
    volumes:
      - ../node-4.json:/helium/config/node.json
      - ../setup.json:/helium/config/setup.json
      - ../compute.json:/helium/config/compute.json
      - ./nodelist.json:/helium/config/nodelist.json

      # Persistent data across container reboots.
      # - node-a-data:/helium/data
    profiles: ["all", "clients"]

  node-5:
    image: heliummpc/helium:latest
    container_name: node-5
    command: -docompute
    volumes:
      - ../node-5.json:/helium/config/node.json
      - ../setup.json:/helium/config/setup.json
      - ../compute.json:/helium/config/compute.json
      - ./nodelist.json:/helium/config/nodelist.json
    profiles: ["all", "clients"]

  node-6:
      image: heliummpc/helium:latest
      container_name: node-6
      command: -docompute
      volumes:
        - ../node-6.json:/helium/config/node.json
        - ../setup.json:/helium/config/setup.json
        - ../compute.json:/helium/config/compute.json
        - ./nodelist.json:/helium/config/nodelist.json
      profiles: ["all", "clients"]

  node-7:
      image: heliummpc/helium:latest
      container_name: node-7
      command: -docompute
      volumes:
        - ../node-7.json:/helium/config/node.json
        - ../setup.json:/helium/config/setup.json
        - ../compute.json:/helium/config/compute.json
        - ./nodelist.json:/helium/config/nodelist.json
      profiles: ["all", "clients"]
# volumes:
  # cloud-data:
  # node-a-data: