version: '3.0'
services:
  node-a:
    image: heliummpc/helium:latest
    container_name: node-a
    command: -setup /helium/config/setup_desc.json
    environment:
      - GRPC_GO_LOG_VERBOSITY_LEVEL=99
      - GRPC_GO_LOG_SEVERITY_LEVEL=info
    volumes:
      - ../nodeA.json:/helium/config/node.json
      - ../setup_desc.json:/helium/config/setup_desc.json
      - ./nodelist.json:/helium/config/nodelist.json
  node-b:
    image: heliummpc/helium:latest
    container_name: node-b
    command: -setup /helium/config/setup_desc.json
    environment:
      - GRPC_GO_LOG_VERBOSITY_LEVEL=99
      - GRPC_GO_LOG_SEVERITY_LEVEL=info
    volumes:
      - ../nodeB.json:/helium/config/node.json
      - ../setup_desc.json:/helium/config/setup_desc.json
      - ./nodelist.json:/helium/config/nodelist.json
