version: '3.0'
services:
  cloud:
    image: heliummpc/helium:latest
    container_name: cloud
    command: -setup /helium/config/setup_desc.json -docompute=false -keepRunning
    volumes:
      - ../cloud.json:/helium/config/node.json
      - ../setup_desc.json:/helium/config/setup_desc.json
      - ./nodelist.json:/helium/config/nodelist.json

      - cloud-data:/helium/data
    profiles: ["all", "cloud"]

  node-a:
    image: heliummpc/helium:latest
    container_name: node-a
    command: -setup /helium/config/setup_desc.json -docompute=false
    volumes:
      - ../nodeA.json:/helium/config/node.json
      - ../setup_desc.json:/helium/config/setup_desc.json
      - ./nodelist.json:/helium/config/nodelist.json

      # Persistent data across container reboots.
      - node-a-data:/helium/data
    profiles: ["all", "clients"]

  node-b:
    image: heliummpc/helium:latest
    container_name: node-b
    command: -setup /helium/config/setup_desc.json -docompute=false
    volumes:
      - ../nodeB.json:/helium/config/node.json
      - ../setup_desc.json:/helium/config/setup_desc.json
      - ./nodelist.json:/helium/config/nodelist.json

      # No persistency.
    profiles: ["all", "clients"]

  node-R:
    image: heliummpc/helium:latest
    container_name: node-R
    command: -setup /helium/config/setup_desc.json -docompute=false
    volumes:
      - ../node-R.json:/helium/config/node.json
      - ../setup_desc.json:/helium/config/setup_desc.json
      - ./nodelist.json:/helium/config/nodelist.json

      # No persistency.
    profiles: ["all", "receiver"]


volumes:
  cloud-data:
  node-a-data: