version: '3.0'
services:
  cloud:
    image: heliummpc/helium:latest
    container_name: cloud
    command: -expDuration 10s
    volumes:
      - ../cloud.json:/helium/config/node.json
      - ./nodelist.json:/helium/config/nodelist.json
    ports:
      - "40000:40000"
      # - cloud-data:/helium/data
    profiles: ["all", "cloud"]

  node-0:
    image: heliummpc/helium:latest
    container_name: node-0
    volumes:
      - ../node-0.json:/helium/config/node.json
      - ./nodelist.json:/helium/config/nodelist.json

      # Persistent data across container reboots.
      # - node-a-data:/helium/data
    profiles: ["all", "clients"]

  node-1:
    image: heliummpc/helium:latest
    container_name: node-1
    volumes:
      - ../node-1.json:/helium/config/node.json
      - ./nodelist.json:/helium/config/nodelist.json

      # No persistency.
    profiles: ["all", "clients"]

  node-2:
    image: heliummpc/helium:latest
    container_name: node-2
    volumes:
      - ../node-2.json:/helium/config/node.json
      - ./nodelist.json:/helium/config/nodelist.json
    profiles: ["all", "clients"]

# volumes:
  # cloud-data:
  # node-a-data: