version: '3.0'
services:
  cloud:
    image: heliummpc/helium:latest
    container_name: cloud
    command: -docompute
    volumes:
      - ../cloud.json:/helium/config/node.json
      - ../setup.json:/helium/config/setup.json
      - ../compute.json:/helium/config/compute.json
      - ./nodelist.json:/helium/config/nodelist.json
      - ../node-R_pk.json:/helium/config/node-R_pk.json

    # profiles: ["all", "cloud"]

  node-0:
    image: heliummpc/helium:latest
    container_name: node-0
    command: -docompute
    volumes:
      - ../node-0.json:/helium/config/node.json
      - ../setup.json:/helium/config/setup.json
      - ../compute.json:/helium/config/compute.json
      - ./nodelist.json:/helium/config/nodelist.json
      - ../node-R_pk.json:/helium/config/node-R_pk.json

    # profiles: ["all", "clients"]

  node-1:
    image: heliummpc/helium:latest
    container_name: node-1
    command: -docompute
    volumes:
      - ../node-1.json:/helium/config/node.json
      - ../setup.json:/helium/config/setup.json
      - ../compute.json:/helium/config/compute.json
      - ./nodelist.json:/helium/config/nodelist.json
      - ../node-R_pk.json:/helium/config/node-R_pk.json

    # profiles: ["all", "clients"]

  # node-R is the external receiver
  node-R:
    image: heliummpc/helium:latest
    container_name: node-R
    command: -docompute -decryptionKeyFile /helium/config/node-R_sk.json
    volumes:
      - ../node-R.json:/helium/config/node.json
      - ../setup.json:/helium/config/setup.json
      - ../compute.json:/helium/config/compute.json
      - ./nodelist.json:/helium/config/nodelist.json
      - ../node-R_pk.json:/helium/config/node-R_pk.json
      - ../node-R_sk.json:/helium/config/node-R_sk.json # only the receiver's volume has access to the decryption key 