// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v3.21.12
// source: helium.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EventType int32

const (
	EventType_Completed EventType = 0
	EventType_Started   EventType = 1
	EventType_Executing EventType = 2
	EventType_Failed    EventType = 3
)

// Enum value maps for EventType.
var (
	EventType_name = map[int32]string{
		0: "Completed",
		1: "Started",
		2: "Executing",
		3: "Failed",
	}
	EventType_value = map[string]int32{
		"Completed": 0,
		"Started":   1,
		"Executing": 2,
		"Failed":    3,
	}
)

func (x EventType) Enum() *EventType {
	p := new(EventType)
	*p = x
	return p
}

func (x EventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EventType) Descriptor() protoreflect.EnumDescriptor {
	return file_helium_proto_enumTypes[0].Descriptor()
}

func (EventType) Type() protoreflect.EnumType {
	return &file_helium_proto_enumTypes[0]
}

func (x EventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EventType.Descriptor instead.
func (EventType) EnumDescriptor() ([]byte, []int) {
	return file_helium_proto_rawDescGZIP(), []int{0}
}

type ProtocolType int32

const (
	ProtocolType_UNSPECIFIED ProtocolType = 0
	ProtocolType_SKG         ProtocolType = 1 // secret-key generation
	ProtocolType_CKG         ProtocolType = 2 // public encryption-key generation
	ProtocolType_RKG_1       ProtocolType = 3 // first round of public relinearization-key generation
	ProtocolType_RKG         ProtocolType = 4 // second round of public relinearization-key generation
	ProtocolType_RTG         ProtocolType = 5 // public rotation-key generation
	ProtocolType_CKS         ProtocolType = 6 // collective switching to collective secret-key
	ProtocolType_DEC         ProtocolType = 7 // collective decryption
	ProtocolType_PCKS        ProtocolType = 8 // collective switching to known public-key
)

// Enum value maps for ProtocolType.
var (
	ProtocolType_name = map[int32]string{
		0: "UNSPECIFIED",
		1: "SKG",
		2: "CKG",
		3: "RKG_1",
		4: "RKG",
		5: "RTG",
		6: "CKS",
		7: "DEC",
		8: "PCKS",
	}
	ProtocolType_value = map[string]int32{
		"UNSPECIFIED": 0,
		"SKG":         1,
		"CKG":         2,
		"RKG_1":       3,
		"RKG":         4,
		"RTG":         5,
		"CKS":         6,
		"DEC":         7,
		"PCKS":        8,
	}
)

func (x ProtocolType) Enum() *ProtocolType {
	p := new(ProtocolType)
	*p = x
	return p
}

func (x ProtocolType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ProtocolType) Descriptor() protoreflect.EnumDescriptor {
	return file_helium_proto_enumTypes[1].Descriptor()
}

func (ProtocolType) Type() protoreflect.EnumType {
	return &file_helium_proto_enumTypes[1]
}

func (x ProtocolType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ProtocolType.Descriptor instead.
func (ProtocolType) EnumDescriptor() ([]byte, []int) {
	return file_helium_proto_rawDescGZIP(), []int{1}
}

type CiphertextType int32

const (
	CiphertextType_UNSPECIFIED_CT_TYPE CiphertextType = 0
	CiphertextType_BFV                 CiphertextType = 1
	CiphertextType_BGV                 CiphertextType = 2
	CiphertextType_CKKS                CiphertextType = 3
	CiphertextType_RGSW                CiphertextType = 4
)

// Enum value maps for CiphertextType.
var (
	CiphertextType_name = map[int32]string{
		0: "UNSPECIFIED_CT_TYPE",
		1: "BFV",
		2: "BGV",
		3: "CKKS",
		4: "RGSW",
	}
	CiphertextType_value = map[string]int32{
		"UNSPECIFIED_CT_TYPE": 0,
		"BFV":                 1,
		"BGV":                 2,
		"CKKS":                3,
		"RGSW":                4,
	}
)

func (x CiphertextType) Enum() *CiphertextType {
	p := new(CiphertextType)
	*p = x
	return p
}

func (x CiphertextType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CiphertextType) Descriptor() protoreflect.EnumDescriptor {
	return file_helium_proto_enumTypes[2].Descriptor()
}

func (CiphertextType) Type() protoreflect.EnumType {
	return &file_helium_proto_enumTypes[2]
}

func (x CiphertextType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CiphertextType.Descriptor instead.
func (CiphertextType) EnumDescriptor() ([]byte, []int) {
	return file_helium_proto_rawDescGZIP(), []int{2}
}

// MESSAGE DEFINITIONS
//
// The following messages have counterparts in the Go implementation of the Helium service.
// See the godoc for more information on these messages.
type Void struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Void) Reset() {
	*x = Void{}
	mi := &file_helium_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Void) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Void) ProtoMessage() {}

func (x *Void) ProtoReflect() protoreflect.Message {
	mi := &file_helium_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Void.ProtoReflect.Descriptor instead.
func (*Void) Descriptor() ([]byte, []int) {
	return file_helium_proto_rawDescGZIP(), []int{0}
}

type ProtocolID struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProtocolID    string                 `protobuf:"bytes,1,opt,name=ProtocolID,proto3" json:"ProtocolID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProtocolID) Reset() {
	*x = ProtocolID{}
	mi := &file_helium_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProtocolID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtocolID) ProtoMessage() {}

func (x *ProtocolID) ProtoReflect() protoreflect.Message {
	mi := &file_helium_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtocolID.ProtoReflect.Descriptor instead.
func (*ProtocolID) Descriptor() ([]byte, []int) {
	return file_helium_proto_rawDescGZIP(), []int{1}
}

func (x *ProtocolID) GetProtocolID() string {
	if x != nil {
		return x.ProtocolID
	}
	return ""
}

type SessionID struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionID) Reset() {
	*x = SessionID{}
	mi := &file_helium_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionID) ProtoMessage() {}

func (x *SessionID) ProtoReflect() protoreflect.Message {
	mi := &file_helium_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionID.ProtoReflect.Descriptor instead.
func (*SessionID) Descriptor() ([]byte, []int) {
	return file_helium_proto_rawDescGZIP(), []int{2}
}

func (x *SessionID) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type NodeID struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeID) Reset() {
	*x = NodeID{}
	mi := &file_helium_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeID) ProtoMessage() {}

func (x *NodeID) ProtoReflect() protoreflect.Message {
	mi := &file_helium_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeID.ProtoReflect.Descriptor instead.
func (*NodeID) Descriptor() ([]byte, []int) {
	return file_helium_proto_rawDescGZIP(), []int{3}
}

func (x *NodeID) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

type CiphertextID struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CiphertextId  string                 `protobuf:"bytes,1,opt,name=ciphertext_id,json=ciphertextId,proto3" json:"ciphertext_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CiphertextID) Reset() {
	*x = CiphertextID{}
	mi := &file_helium_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CiphertextID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CiphertextID) ProtoMessage() {}

func (x *CiphertextID) ProtoReflect() protoreflect.Message {
	mi := &file_helium_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CiphertextID.ProtoReflect.Descriptor instead.
func (*CiphertextID) Descriptor() ([]byte, []int) {
	return file_helium_proto_rawDescGZIP(), []int{4}
}

func (x *CiphertextID) GetCiphertextId() string {
	if x != nil {
		return x.CiphertextId
	}
	return ""
}

type ProtocolEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Descriptor_   *ProtocolDescriptor    `protobuf:"bytes,1,opt,name=Descriptor,proto3" json:"Descriptor,omitempty"`
	Type          EventType              `protobuf:"varint,2,opt,name=Type,proto3,enum=helium_proto.EventType" json:"Type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProtocolEvent) Reset() {
	*x = ProtocolEvent{}
	mi := &file_helium_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProtocolEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtocolEvent) ProtoMessage() {}

func (x *ProtocolEvent) ProtoReflect() protoreflect.Message {
	mi := &file_helium_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtocolEvent.ProtoReflect.Descriptor instead.
func (*ProtocolEvent) Descriptor() ([]byte, []int) {
	return file_helium_proto_rawDescGZIP(), []int{5}
}

func (x *ProtocolEvent) GetDescriptor_() *ProtocolDescriptor {
	if x != nil {
		return x.Descriptor_
	}
	return nil
}

func (x *ProtocolEvent) GetType() EventType {
	if x != nil {
		return x.Type
	}
	return EventType_Completed
}

type CircuitEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Descriptor_   *CircuitDescriptor     `protobuf:"bytes,1,opt,name=Descriptor,proto3" json:"Descriptor,omitempty"`
	Type          EventType              `protobuf:"varint,2,opt,name=Type,proto3,enum=helium_proto.EventType" json:"Type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CircuitEvent) Reset() {
	*x = CircuitEvent{}
	mi := &file_helium_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CircuitEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CircuitEvent) ProtoMessage() {}

func (x *CircuitEvent) ProtoReflect() protoreflect.Message {
	mi := &file_helium_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CircuitEvent.ProtoReflect.Descriptor instead.
func (*CircuitEvent) Descriptor() ([]byte, []int) {
	return file_helium_proto_rawDescGZIP(), []int{6}
}

func (x *CircuitEvent) GetDescriptor_() *CircuitDescriptor {
	if x != nil {
		return x.Descriptor_
	}
	return nil
}

func (x *CircuitEvent) GetType() EventType {
	if x != nil {
		return x.Type
	}
	return EventType_Completed
}

// NodeEvent is an event of the node-level coordination log: either a protocol
// event (emitted by the coordinator and the protocol runner) or a circuit event
// (emitted by the circuit evaluator).
type NodeEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Event:
	//
	//	*NodeEvent_ProtocolEvent
	//	*NodeEvent_CircuitEvent
	Event         isNodeEvent_Event `protobuf_oneof:"Event"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeEvent) Reset() {
	*x = NodeEvent{}
	mi := &file_helium_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeEvent) ProtoMessage() {}

func (x *NodeEvent) ProtoReflect() protoreflect.Message {
	mi := &file_helium_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeEvent.ProtoReflect.Descriptor instead.
func (*NodeEvent) Descriptor() ([]byte, []int) {
	return file_helium_proto_rawDescGZIP(), []int{7}
}

func (x *NodeEvent) GetEvent() isNodeEvent_Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *NodeEvent) GetProtocolEvent() *ProtocolEvent {
	if x != nil {
		if x, ok := x.Event.(*NodeEvent_ProtocolEvent); ok {
			return x.ProtocolEvent
		}
	}
	return nil
}

func (x *NodeEvent) GetCircuitEvent() *CircuitEvent {
	if x != nil {
		if x, ok := x.Event.(*NodeEvent_CircuitEvent); ok {
			return x.CircuitEvent
		}
	}
	return nil
}

type isNodeEvent_Event interface {
	isNodeEvent_Event()
}

type NodeEvent_ProtocolEvent struct {
	ProtocolEvent *ProtocolEvent `protobuf:"bytes,1,opt,name=ProtocolEvent,proto3,oneof"`
}

type NodeEvent_CircuitEvent struct {
	CircuitEvent *CircuitEvent `protobuf:"bytes,2,opt,name=CircuitEvent,proto3,oneof"`
}

func (*NodeEvent_ProtocolEvent) isNodeEvent_Event() {}

func (*NodeEvent_CircuitEvent) isNodeEvent_Event() {}

type ProtocolDescriptor struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProtocolType  ProtocolType           `protobuf:"varint,1,opt,name=ProtocolType,proto3,enum=helium_proto.ProtocolType" json:"ProtocolType,omitempty"`
	Args          map[string]string      `protobuf:"bytes,2,rep,name=Args,proto3" json:"Args,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Aggregator    *NodeID                `protobuf:"bytes,3,opt,name=Aggregator,proto3" json:"Aggregator,omitempty"`
	Participants  []*NodeID              `protobuf:"bytes,4,rep,name=Participants,proto3" json:"Participants,omitempty"`
	Receivers     []*NodeID              `protobuf:"bytes,5,rep,name=Receivers,proto3" json:"Receivers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProtocolDescriptor) Reset() {
	*x = ProtocolDescriptor{}
	mi := &file_helium_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProtocolDescriptor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtocolDescriptor) ProtoMessage() {}

func (x *ProtocolDescriptor) ProtoReflect() protoreflect.Message {
	mi := &file_helium_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtocolDescriptor.ProtoReflect.Descriptor instead.
func (*ProtocolDescriptor) Descriptor() ([]byte, []int) {
	return file_helium_proto_rawDescGZIP(), []int{8}
}

func (x *ProtocolDescriptor) GetProtocolType() ProtocolType {
	if x != nil {
		return x.ProtocolType
	}
	return ProtocolType_UNSPECIFIED
}

func (x *ProtocolDescriptor) GetArgs() map[string]string {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *ProtocolDescriptor) GetAggregator() *NodeID {
	if x != nil {
		return x.Aggregator
	}
	return nil
}

func (x *ProtocolDescriptor) GetParticipants() []*NodeID {
	if x != nil {
		return x.Participants
	}
	return nil
}

func (x *ProtocolDescriptor) GetReceivers() []*NodeID {
	if x != nil {
		return x.Receivers
	}
	return nil
}

type ShareMetadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProtocolID    *ProtocolID            `protobuf:"bytes,1,opt,name=ProtocolID,proto3" json:"ProtocolID,omitempty"`
	ProtocolType  ProtocolType           `protobuf:"varint,2,opt,name=ProtocolType,proto3,enum=helium_proto.ProtocolType" json:"ProtocolType,omitempty"`
	AggregateFor  []*NodeID              `protobuf:"bytes,3,rep,name=AggregateFor,proto3" json:"AggregateFor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShareMetadata) Reset() {
	*x = ShareMetadata{}
	mi := &file_helium_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShareMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShareMetadata) ProtoMessage() {}

func (x *ShareMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_helium_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShareMetadata.ProtoReflect.Descriptor instead.
func (*ShareMetadata) Descriptor() ([]byte, []int) {
	return file_helium_proto_rawDescGZIP(), []int{9}
}

func (x *ShareMetadata) GetProtocolID() *ProtocolID {
	if x != nil {
		return x.ProtocolID
	}
	return nil
}

func (x *ShareMetadata) GetProtocolType() ProtocolType {
	if x != nil {
		return x.ProtocolType
	}
	return ProtocolType_UNSPECIFIED
}

func (x *ShareMetadata) GetAggregateFor() []*NodeID {
	if x != nil {
		return x.AggregateFor
	}
	return nil
}

type Share struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metadata      *ShareMetadata         `protobuf:"bytes,1,opt,name=Metadata,proto3" json:"Metadata,omitempty"`
	Share         []byte                 `protobuf:"bytes,2,opt,name=share,proto3" json:"share,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Share) Reset() {
	*x = Share{}
	mi := &file_helium_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Share) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Share) ProtoMessage() {}

func (x *Share) ProtoReflect() protoreflect.Message {
	mi := &file_helium_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Share.ProtoReflect.Descriptor instead.
func (*Share) Descriptor() ([]byte, []int) {
	return file_helium_proto_rawDescGZIP(), []int{10}
}

func (x *Share) GetMetadata() *ShareMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *Share) GetShare() []byte {
	if x != nil {
		return x.Share
	}
	return nil
}

type AggregationOutput struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	AggregatedShare *Share                 `protobuf:"bytes,1,opt,name=AggregatedShare,proto3" json:"AggregatedShare,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AggregationOutput) Reset() {
	*x = AggregationOutput{}
	mi := &file_helium_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AggregationOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AggregationOutput) ProtoMessage() {}

func (x *AggregationOutput) ProtoReflect() protoreflect.Message {
	mi := &file_helium_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AggregationOutput.ProtoReflect.Descriptor instead.
func (*AggregationOutput) Descriptor() ([]byte, []int) {
	return file_helium_proto_rawDescGZIP(), []int{11}
}

func (x *AggregationOutput) GetAggregatedShare() *Share {
	if x != nil {
		return x.AggregatedShare
	}
	return nil
}

type CircuitSignature struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Args          map[string]string      `protobuf:"bytes,2,rep,name=Args,proto3" json:"Args,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CircuitSignature) Reset() {
	*x = CircuitSignature{}
	mi := &file_helium_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CircuitSignature) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CircuitSignature) ProtoMessage() {}

func (x *CircuitSignature) ProtoReflect() protoreflect.Message {
	mi := &file_helium_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CircuitSignature.ProtoReflect.Descriptor instead.
func (*CircuitSignature) Descriptor() ([]byte, []int) {
	return file_helium_proto_rawDescGZIP(), []int{12}
}

func (x *CircuitSignature) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CircuitSignature) GetArgs() map[string]string {
	if x != nil {
		return x.Args
	}
	return nil
}

type CircuitID struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CircuitID     string                 `protobuf:"bytes,1,opt,name=CircuitID,proto3" json:"CircuitID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CircuitID) Reset() {
	*x = CircuitID{}
	mi := &file_helium_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CircuitID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CircuitID) ProtoMessage() {}

func (x *CircuitID) ProtoReflect() protoreflect.Message {
	mi := &file_helium_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CircuitID.ProtoReflect.Descriptor instead.
func (*CircuitID) Descriptor() ([]byte, []int) {
	return file_helium_proto_rawDescGZIP(), []int{13}
}

func (x *CircuitID) GetCircuitID() string {
	if x != nil {
		return x.CircuitID
	}
	return ""
}

type CircuitDescriptor struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	CircuitSignature *CircuitSignature      `protobuf:"bytes,1,opt,name=CircuitSignature,proto3" json:"CircuitSignature,omitempty"`
	CircuitID        *CircuitID             `protobuf:"bytes,2,opt,name=CircuitID,proto3" json:"CircuitID,omitempty"`
	NodeMapping      map[string]*NodeID     `protobuf:"bytes,3,rep,name=NodeMapping,proto3" json:"NodeMapping,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Evaluator        *NodeID                `protobuf:"bytes,4,opt,name=Evaluator,proto3" json:"Evaluator,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CircuitDescriptor) Reset() {
	*x = CircuitDescriptor{}
	mi := &file_helium_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CircuitDescriptor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CircuitDescriptor) ProtoMessage() {}

func (x *CircuitDescriptor) ProtoReflect() protoreflect.Message {
	mi := &file_helium_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CircuitDescriptor.ProtoReflect.Descriptor instead.
func (*CircuitDescriptor) Descriptor() ([]byte, []int) {
	return file_helium_proto_rawDescGZIP(), []int{14}
}

func (x *CircuitDescriptor) GetCircuitSignature() *CircuitSignature {
	if x != nil {
		return x.CircuitSignature
	}
	return nil
}

func (x *CircuitDescriptor) GetCircuitID() *CircuitID {
	if x != nil {
		return x.CircuitID
	}
	return nil
}

func (x *CircuitDescriptor) GetNodeMapping() map[string]*NodeID {
	if x != nil {
		return x.NodeMapping
	}
	return nil
}

func (x *CircuitDescriptor) GetEvaluator() *NodeID {
	if x != nil {
		return x.Evaluator
	}
	return nil
}

type Ciphertext struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ciphertext    []byte                 `protobuf:"bytes,1,opt,name=ciphertext,proto3" json:"ciphertext,omitempty"`
	Metadata      *CiphertextMetadata    `protobuf:"bytes,2,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ciphertext) Reset() {
	*x = Ciphertext{}
	mi := &file_helium_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ciphertext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ciphertext) ProtoMessage() {}

func (x *Ciphertext) ProtoReflect() protoreflect.Message {
	mi := &file_helium_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ciphertext.ProtoReflect.Descriptor instead.
func (*Ciphertext) Descriptor() ([]byte, []int) {
	return file_helium_proto_rawDescGZIP(), []int{15}
}

func (x *Ciphertext) GetCiphertext() []byte {
	if x != nil {
		return x.Ciphertext
	}
	return nil
}

func (x *Ciphertext) GetMetadata() *CiphertextMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type CiphertextMetadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            *CiphertextID          `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type          *CiphertextType        `protobuf:"varint,2,opt,name=type,proto3,enum=helium_proto.CiphertextType,oneof" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CiphertextMetadata) Reset() {
	*x = CiphertextMetadata{}
	mi := &file_helium_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CiphertextMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CiphertextMetadata) ProtoMessage() {}

func (x *CiphertextMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_helium_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CiphertextMetadata.ProtoReflect.Descriptor instead.
func (*CiphertextMetadata) Descriptor() ([]byte, []int) {
	return file_helium_proto_rawDescGZIP(), []int{16}
}

func (x *CiphertextMetadata) GetId() *CiphertextID {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *CiphertextMetadata) GetType() CiphertextType {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return CiphertextType_UNSPECIFIED_CT_TYPE
}

var File_helium_proto protoreflect.FileDescriptor

const file_helium_proto_rawDesc = "" +
	"\n" +
	"\fhelium.proto\x12\fhelium_proto\"\x06\n" +
	"\x04Void\",\n" +
	"\n" +
	"ProtocolID\x12\x1e\n" +
	"\n" +
	"ProtocolID\x18\x01 \x01(\tR\n" +
	"ProtocolID\"*\n" +
	"\tSessionID\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"!\n" +
	"\x06NodeID\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\"3\n" +
	"\fCiphertextID\x12#\n" +
	"\rciphertext_id\x18\x01 \x01(\tR\fciphertextId\"~\n" +
	"\rProtocolEvent\x12@\n" +
	"\n" +
	"Descriptor\x18\x01 \x01(\v2 .helium_proto.ProtocolDescriptorR\n" +
	"Descriptor\x12+\n" +
	"\x04Type\x18\x02 \x01(\x0e2\x17.helium_proto.EventTypeR\x04Type\"|\n" +
	"\fCircuitEvent\x12?\n" +
	"\n" +
	"Descriptor\x18\x01 \x01(\v2\x1f.helium_proto.CircuitDescriptorR\n" +
	"Descriptor\x12+\n" +
	"\x04Type\x18\x02 \x01(\x0e2\x17.helium_proto.EventTypeR\x04Type\"\x9b\x01\n" +
	"\tNodeEvent\x12C\n" +
	"\rProtocolEvent\x18\x01 \x01(\v2\x1b.helium_proto.ProtocolEventH\x00R\rProtocolEvent\x12@\n" +
	"\fCircuitEvent\x18\x02 \x01(\v2\x1a.helium_proto.CircuitEventH\x00R\fCircuitEventB\a\n" +
	"\x05Event\"\xf1\x02\n" +
	"\x12ProtocolDescriptor\x12>\n" +
	"\fProtocolType\x18\x01 \x01(\x0e2\x1a.helium_proto.ProtocolTypeR\fProtocolType\x12>\n" +
	"\x04Args\x18\x02 \x03(\v2*.helium_proto.ProtocolDescriptor.ArgsEntryR\x04Args\x124\n" +
	"\n" +
	"Aggregator\x18\x03 \x01(\v2\x14.helium_proto.NodeIDR\n" +
	"Aggregator\x128\n" +
	"\fParticipants\x18\x04 \x03(\v2\x14.helium_proto.NodeIDR\fParticipants\x122\n" +
	"\tReceivers\x18\x05 \x03(\v2\x14.helium_proto.NodeIDR\tReceivers\x1a7\n" +
	"\tArgsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xc3\x01\n" +
	"\rShareMetadata\x128\n" +
	"\n" +
	"ProtocolID\x18\x01 \x01(\v2\x18.helium_proto.ProtocolIDR\n" +
	"ProtocolID\x12>\n" +
	"\fProtocolType\x18\x02 \x01(\x0e2\x1a.helium_proto.ProtocolTypeR\fProtocolType\x128\n" +
	"\fAggregateFor\x18\x03 \x03(\v2\x14.helium_proto.NodeIDR\fAggregateFor\"V\n" +
	"\x05Share\x127\n" +
	"\bMetadata\x18\x01 \x01(\v2\x1b.helium_proto.ShareMetadataR\bMetadata\x12\x14\n" +
	"\x05share\x18\x02 \x01(\fR\x05share\"R\n" +
	"\x11AggregationOutput\x12=\n" +
	"\x0fAggregatedShare\x18\x01 \x01(\v2\x13.helium_proto.ShareR\x0fAggregatedShare\"\x9d\x01\n" +
	"\x10CircuitSignature\x12\x12\n" +
	"\x04Name\x18\x01 \x01(\tR\x04Name\x12<\n" +
	"\x04Args\x18\x02 \x03(\v2(.helium_proto.CircuitSignature.ArgsEntryR\x04Args\x1a7\n" +
	"\tArgsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\")\n" +
	"\tCircuitID\x12\x1c\n" +
	"\tCircuitID\x18\x01 \x01(\tR\tCircuitID\"\xf4\x02\n" +
	"\x11CircuitDescriptor\x12J\n" +
	"\x10CircuitSignature\x18\x01 \x01(\v2\x1e.helium_proto.CircuitSignatureR\x10CircuitSignature\x125\n" +
	"\tCircuitID\x18\x02 \x01(\v2\x17.helium_proto.CircuitIDR\tCircuitID\x12R\n" +
	"\vNodeMapping\x18\x03 \x03(\v20.helium_proto.CircuitDescriptor.NodeMappingEntryR\vNodeMapping\x122\n" +
	"\tEvaluator\x18\x04 \x01(\v2\x14.helium_proto.NodeIDR\tEvaluator\x1aT\n" +
	"\x10NodeMappingEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12*\n" +
	"\x05value\x18\x02 \x01(\v2\x14.helium_proto.NodeIDR\x05value:\x028\x01\"j\n" +
	"\n" +
	"Ciphertext\x12\x1e\n" +
	"\n" +
	"ciphertext\x18\x01 \x01(\fR\n" +
	"ciphertext\x12<\n" +
	"\bmetadata\x18\x02 \x01(\v2 .helium_proto.CiphertextMetadataR\bmetadata\"\x80\x01\n" +
	"\x12CiphertextMetadata\x12*\n" +
	"\x02id\x18\x01 \x01(\v2\x1a.helium_proto.CiphertextIDR\x02id\x125\n" +
	"\x04type\x18\x02 \x01(\x0e2\x1c.helium_proto.CiphertextTypeH\x00R\x04type\x88\x01\x01B\a\n" +
	"\x05_type*B\n" +
	"\tEventType\x12\r\n" +
	"\tCompleted\x10\x00\x12\v\n" +
	"\aStarted\x10\x01\x12\r\n" +
	"\tExecuting\x10\x02\x12\n" +
	"\n" +
	"\x06Failed\x10\x03*j\n" +
	"\fProtocolType\x12\x0f\n" +
	"\vUNSPECIFIED\x10\x00\x12\a\n" +
	"\x03SKG\x10\x01\x12\a\n" +
	"\x03CKG\x10\x02\x12\t\n" +
	"\x05RKG_1\x10\x03\x12\a\n" +
	"\x03RKG\x10\x04\x12\a\n" +
	"\x03RTG\x10\x05\x12\a\n" +
	"\x03CKS\x10\x06\x12\a\n" +
	"\x03DEC\x10\a\x12\b\n" +
	"\x04PCKS\x10\b*O\n" +
	"\x0eCiphertextType\x12\x17\n" +
	"\x13UNSPECIFIED_CT_TYPE\x10\x00\x12\a\n" +
	"\x03BFV\x10\x01\x12\a\n" +
	"\x03BGV\x10\x02\x12\b\n" +
	"\x04CKKS\x10\x03\x12\b\n" +
	"\x04RGSW\x10\x042\xaf\x03\n" +
	"\x06Helium\x129\n" +
	"\bRegister\x12\x12.helium_proto.Void\x1a\x17.helium_proto.NodeEvent0\x01\x125\n" +
	"\bPutShare\x12\x13.helium_proto.Share\x1a\x12.helium_proto.Void\"\x00\x12[\n" +
	"\x14GetAggregationOutput\x12 .helium_proto.ProtocolDescriptor\x1a\x1f.helium_proto.AggregationOutput\"\x00\x12G\n" +
	"\rGetCiphertext\x12\x1a.helium_proto.CiphertextID\x1a\x18.helium_proto.Ciphertext\"\x00\x12G\n" +
	"\rPutCiphertext\x12\x18.helium_proto.Ciphertext\x1a\x1a.helium_proto.CiphertextID\"\x00\x12D\n" +
	"\vEvalCircuit\x12\x1f.helium_proto.CircuitDescriptor\x1a\x12.helium_proto.Void\"\x00B'Z%github.com/ChristianMct/helium/api/pbb\x06proto3"

var (
	file_helium_proto_rawDescOnce sync.Once
	file_helium_proto_rawDescData []byte
)

func file_helium_proto_rawDescGZIP() []byte {
	file_helium_proto_rawDescOnce.Do(func() {
		file_helium_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_helium_proto_rawDesc), len(file_helium_proto_rawDesc)))
	})
	return file_helium_proto_rawDescData
}

var file_helium_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_helium_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_helium_proto_goTypes = []any{
	(EventType)(0),             // 0: helium_proto.EventType
	(ProtocolType)(0),          // 1: helium_proto.ProtocolType
	(CiphertextType)(0),        // 2: helium_proto.CiphertextType
	(*Void)(nil),               // 3: helium_proto.Void
	(*ProtocolID)(nil),         // 4: helium_proto.ProtocolID
	(*SessionID)(nil),          // 5: helium_proto.SessionID
	(*NodeID)(nil),             // 6: helium_proto.NodeID
	(*CiphertextID)(nil),       // 7: helium_proto.CiphertextID
	(*ProtocolEvent)(nil),      // 8: helium_proto.ProtocolEvent
	(*CircuitEvent)(nil),       // 9: helium_proto.CircuitEvent
	(*NodeEvent)(nil),          // 10: helium_proto.NodeEvent
	(*ProtocolDescriptor)(nil), // 11: helium_proto.ProtocolDescriptor
	(*ShareMetadata)(nil),      // 12: helium_proto.ShareMetadata
	(*Share)(nil),              // 13: helium_proto.Share
	(*AggregationOutput)(nil),  // 14: helium_proto.AggregationOutput
	(*CircuitSignature)(nil),   // 15: helium_proto.CircuitSignature
	(*CircuitID)(nil),          // 16: helium_proto.CircuitID
	(*CircuitDescriptor)(nil),  // 17: helium_proto.CircuitDescriptor
	(*Ciphertext)(nil),         // 18: helium_proto.Ciphertext
	(*CiphertextMetadata)(nil), // 19: helium_proto.CiphertextMetadata
	nil,                        // 20: helium_proto.ProtocolDescriptor.ArgsEntry
	nil,                        // 21: helium_proto.CircuitSignature.ArgsEntry
	nil,                        // 22: helium_proto.CircuitDescriptor.NodeMappingEntry
}
var file_helium_proto_depIdxs = []int32{
	11, // 0: helium_proto.ProtocolEvent.Descriptor:type_name -> helium_proto.ProtocolDescriptor
	0,  // 1: helium_proto.ProtocolEvent.Type:type_name -> helium_proto.EventType
	17, // 2: helium_proto.CircuitEvent.Descriptor:type_name -> helium_proto.CircuitDescriptor
	0,  // 3: helium_proto.CircuitEvent.Type:type_name -> helium_proto.EventType
	8,  // 4: helium_proto.NodeEvent.ProtocolEvent:type_name -> helium_proto.ProtocolEvent
	9,  // 5: helium_proto.NodeEvent.CircuitEvent:type_name -> helium_proto.CircuitEvent
	1,  // 6: helium_proto.ProtocolDescriptor.ProtocolType:type_name -> helium_proto.ProtocolType
	20, // 7: helium_proto.ProtocolDescriptor.Args:type_name -> helium_proto.ProtocolDescriptor.ArgsEntry
	6,  // 8: helium_proto.ProtocolDescriptor.Aggregator:type_name -> helium_proto.NodeID
	6,  // 9: helium_proto.ProtocolDescriptor.Participants:type_name -> helium_proto.NodeID
	6,  // 10: helium_proto.ProtocolDescriptor.Receivers:type_name -> helium_proto.NodeID
	4,  // 11: helium_proto.ShareMetadata.ProtocolID:type_name -> helium_proto.ProtocolID
	1,  // 12: helium_proto.ShareMetadata.ProtocolType:type_name -> helium_proto.ProtocolType
	6,  // 13: helium_proto.ShareMetadata.AggregateFor:type_name -> helium_proto.NodeID
	12, // 14: helium_proto.Share.Metadata:type_name -> helium_proto.ShareMetadata
	13, // 15: helium_proto.AggregationOutput.AggregatedShare:type_name -> helium_proto.Share
	21, // 16: helium_proto.CircuitSignature.Args:type_name -> helium_proto.CircuitSignature.ArgsEntry
	15, // 17: helium_proto.CircuitDescriptor.CircuitSignature:type_name -> helium_proto.CircuitSignature
	16, // 18: helium_proto.CircuitDescriptor.CircuitID:type_name -> helium_proto.CircuitID
	22, // 19: helium_proto.CircuitDescriptor.NodeMapping:type_name -> helium_proto.CircuitDescriptor.NodeMappingEntry
	6,  // 20: helium_proto.CircuitDescriptor.Evaluator:type_name -> helium_proto.NodeID
	19, // 21: helium_proto.Ciphertext.metadata:type_name -> helium_proto.CiphertextMetadata
	7,  // 22: helium_proto.CiphertextMetadata.id:type_name -> helium_proto.CiphertextID
	2,  // 23: helium_proto.CiphertextMetadata.type:type_name -> helium_proto.CiphertextType
	6,  // 24: helium_proto.CircuitDescriptor.NodeMappingEntry.value:type_name -> helium_proto.NodeID
	3,  // 25: helium_proto.Helium.Register:input_type -> helium_proto.Void
	13, // 26: helium_proto.Helium.PutShare:input_type -> helium_proto.Share
	11, // 27: helium_proto.Helium.GetAggregationOutput:input_type -> helium_proto.ProtocolDescriptor
	7,  // 28: helium_proto.Helium.GetCiphertext:input_type -> helium_proto.CiphertextID
	18, // 29: helium_proto.Helium.PutCiphertext:input_type -> helium_proto.Ciphertext
	17, // 30: helium_proto.Helium.EvalCircuit:input_type -> helium_proto.CircuitDescriptor
	10, // 31: helium_proto.Helium.Register:output_type -> helium_proto.NodeEvent
	3,  // 32: helium_proto.Helium.PutShare:output_type -> helium_proto.Void
	14, // 33: helium_proto.Helium.GetAggregationOutput:output_type -> helium_proto.AggregationOutput
	18, // 34: helium_proto.Helium.GetCiphertext:output_type -> helium_proto.Ciphertext
	7,  // 35: helium_proto.Helium.PutCiphertext:output_type -> helium_proto.CiphertextID
	3,  // 36: helium_proto.Helium.EvalCircuit:output_type -> helium_proto.Void
	31, // [31:37] is the sub-list for method output_type
	25, // [25:31] is the sub-list for method input_type
	25, // [25:25] is the sub-list for extension type_name
	25, // [25:25] is the sub-list for extension extendee
	0,  // [0:25] is the sub-list for field type_name
}

func init() { file_helium_proto_init() }
func file_helium_proto_init() {
	if File_helium_proto != nil {
		return
	}
	file_helium_proto_msgTypes[7].OneofWrappers = []any{
		(*NodeEvent_ProtocolEvent)(nil),
		(*NodeEvent_CircuitEvent)(nil),
	}
	file_helium_proto_msgTypes[16].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_helium_proto_rawDesc), len(file_helium_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_helium_proto_goTypes,
		DependencyIndexes: file_helium_proto_depIdxs,
		EnumInfos:         file_helium_proto_enumTypes,
		MessageInfos:      file_helium_proto_msgTypes,
	}.Build()
	File_helium_proto = out.File
	file_helium_proto_goTypes = nil
	file_helium_proto_depIdxs = nil
}
