// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.21.12
// source: helium.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Helium_Register_FullMethodName             = "/helium_proto.Helium/Register"
	Helium_PutShare_FullMethodName             = "/helium_proto.Helium/PutShare"
	Helium_GetAggregationOutput_FullMethodName = "/helium_proto.Helium/GetAggregationOutput"
	Helium_GetCiphertext_FullMethodName        = "/helium_proto.Helium/GetCiphertext"
	Helium_PutCiphertext_FullMethodName        = "/helium_proto.Helium/PutCiphertext"
	Helium_EvalCircuit_FullMethodName          = "/helium_proto.Helium/EvalCircuit"
)

// HeliumClient is the client API for Helium service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Helium is a service run helium nodes. In the current implementation, only
// the helper node runs this service and acts as a centralized transport/coordinator/
// aggregator and evaluator for its peer nodes.
type HeliumClient interface {
	// Register registers the caller as a peer node to the helium server
	Register(ctx context.Context, in *Void, opts ...grpc.CallOption) (grpc.ServerStreamingClient[NodeEvent], error)
	// PutShare pushes the caller's share in the protocol described by the Share.ShareDescriptor
	//field to the callee.
	PutShare(ctx context.Context, in *Share, opts ...grpc.CallOption) (*Void, error)
	// GetShare queries the aggregation output of the protocol described by PrototocolDescriptor
	GetAggregationOutput(ctx context.Context, in *ProtocolDescriptor, opts ...grpc.CallOption) (*AggregationOutput, error)
	// GetCiphertext queries the ciphertext with the given ID from the callee
	GetCiphertext(ctx context.Context, in *CiphertextID, opts ...grpc.CallOption) (*Ciphertext, error)
	// PutCiphertext pushes the ciphertext to the callee
	PutCiphertext(ctx context.Context, in *Ciphertext, opts ...grpc.CallOption) (*CiphertextID, error)
	// EvalCircuit requests the evaluation of the circuit described by the CircuitDescriptor
	EvalCircuit(ctx context.Context, in *CircuitDescriptor, opts ...grpc.CallOption) (*Void, error)
}

type heliumClient struct {
	cc grpc.ClientConnInterface
}

func NewHeliumClient(cc grpc.ClientConnInterface) HeliumClient {
	return &heliumClient{cc}
}

func (c *heliumClient) Register(ctx context.Context, in *Void, opts ...grpc.CallOption) (grpc.ServerStreamingClient[NodeEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Helium_ServiceDesc.Streams[0], Helium_Register_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Void, NodeEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Helium_RegisterClient = grpc.ServerStreamingClient[NodeEvent]

func (c *heliumClient) PutShare(ctx context.Context, in *Share, opts ...grpc.CallOption) (*Void, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Void)
	err := c.cc.Invoke(ctx, Helium_PutShare_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *heliumClient) GetAggregationOutput(ctx context.Context, in *ProtocolDescriptor, opts ...grpc.CallOption) (*AggregationOutput, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AggregationOutput)
	err := c.cc.Invoke(ctx, Helium_GetAggregationOutput_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *heliumClient) GetCiphertext(ctx context.Context, in *CiphertextID, opts ...grpc.CallOption) (*Ciphertext, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Ciphertext)
	err := c.cc.Invoke(ctx, Helium_GetCiphertext_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *heliumClient) PutCiphertext(ctx context.Context, in *Ciphertext, opts ...grpc.CallOption) (*CiphertextID, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CiphertextID)
	err := c.cc.Invoke(ctx, Helium_PutCiphertext_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *heliumClient) EvalCircuit(ctx context.Context, in *CircuitDescriptor, opts ...grpc.CallOption) (*Void, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Void)
	err := c.cc.Invoke(ctx, Helium_EvalCircuit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HeliumServer is the server API for Helium service.
// All implementations must embed UnimplementedHeliumServer
// for forward compatibility.
//
// Helium is a service run helium nodes. In the current implementation, only
// the helper node runs this service and acts as a centralized transport/coordinator/
// aggregator and evaluator for its peer nodes.
type HeliumServer interface {
	// Register registers the caller as a peer node to the helium server
	Register(*Void, grpc.ServerStreamingServer[NodeEvent]) error
	// PutShare pushes the caller's share in the protocol described by the Share.ShareDescriptor
	//field to the callee.
	PutShare(context.Context, *Share) (*Void, error)
	// GetShare queries the aggregation output of the protocol described by PrototocolDescriptor
	GetAggregationOutput(context.Context, *ProtocolDescriptor) (*AggregationOutput, error)
	// GetCiphertext queries the ciphertext with the given ID from the callee
	GetCiphertext(context.Context, *CiphertextID) (*Ciphertext, error)
	// PutCiphertext pushes the ciphertext to the callee
	PutCiphertext(context.Context, *Ciphertext) (*CiphertextID, error)
	// EvalCircuit requests the evaluation of the circuit described by the CircuitDescriptor
	EvalCircuit(context.Context, *CircuitDescriptor) (*Void, error)
	mustEmbedUnimplementedHeliumServer()
}

// UnimplementedHeliumServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedHeliumServer struct{}

func (UnimplementedHeliumServer) Register(*Void, grpc.ServerStreamingServer[NodeEvent]) error {
	return status.Error(codes.Unimplemented, "method Register not implemented")
}
func (UnimplementedHeliumServer) PutShare(context.Context, *Share) (*Void, error) {
	return nil, status.Error(codes.Unimplemented, "method PutShare not implemented")
}
func (UnimplementedHeliumServer) GetAggregationOutput(context.Context, *ProtocolDescriptor) (*AggregationOutput, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAggregationOutput not implemented")
}
func (UnimplementedHeliumServer) GetCiphertext(context.Context, *CiphertextID) (*Ciphertext, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCiphertext not implemented")
}
func (UnimplementedHeliumServer) PutCiphertext(context.Context, *Ciphertext) (*CiphertextID, error) {
	return nil, status.Error(codes.Unimplemented, "method PutCiphertext not implemented")
}
func (UnimplementedHeliumServer) EvalCircuit(context.Context, *CircuitDescriptor) (*Void, error) {
	return nil, status.Error(codes.Unimplemented, "method EvalCircuit not implemented")
}
func (UnimplementedHeliumServer) mustEmbedUnimplementedHeliumServer() {}
func (UnimplementedHeliumServer) testEmbeddedByValue()                {}

// UnsafeHeliumServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HeliumServer will
// result in compilation errors.
type UnsafeHeliumServer interface {
	mustEmbedUnimplementedHeliumServer()
}

func RegisterHeliumServer(s grpc.ServiceRegistrar, srv HeliumServer) {
	// If the following call panics, it indicates UnimplementedHeliumServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Helium_ServiceDesc, srv)
}

func _Helium_Register_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Void)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(HeliumServer).Register(m, &grpc.GenericServerStream[Void, NodeEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Helium_RegisterServer = grpc.ServerStreamingServer[NodeEvent]

func _Helium_PutShare_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Share)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HeliumServer).PutShare(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Helium_PutShare_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HeliumServer).PutShare(ctx, req.(*Share))
	}
	return interceptor(ctx, in, info, handler)
}

func _Helium_GetAggregationOutput_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProtocolDescriptor)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HeliumServer).GetAggregationOutput(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Helium_GetAggregationOutput_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HeliumServer).GetAggregationOutput(ctx, req.(*ProtocolDescriptor))
	}
	return interceptor(ctx, in, info, handler)
}

func _Helium_GetCiphertext_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CiphertextID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HeliumServer).GetCiphertext(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Helium_GetCiphertext_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HeliumServer).GetCiphertext(ctx, req.(*CiphertextID))
	}
	return interceptor(ctx, in, info, handler)
}

func _Helium_PutCiphertext_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Ciphertext)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HeliumServer).PutCiphertext(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Helium_PutCiphertext_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HeliumServer).PutCiphertext(ctx, req.(*Ciphertext))
	}
	return interceptor(ctx, in, info, handler)
}

func _Helium_EvalCircuit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CircuitDescriptor)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HeliumServer).EvalCircuit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Helium_EvalCircuit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HeliumServer).EvalCircuit(ctx, req.(*CircuitDescriptor))
	}
	return interceptor(ctx, in, info, handler)
}

// Helium_ServiceDesc is the grpc.ServiceDesc for Helium service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Helium_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "helium_proto.Helium",
	HandlerType: (*HeliumServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PutShare",
			Handler:    _Helium_PutShare_Handler,
		},
		{
			MethodName: "GetAggregationOutput",
			Handler:    _Helium_GetAggregationOutput_Handler,
		},
		{
			MethodName: "GetCiphertext",
			Handler:    _Helium_GetCiphertext_Handler,
		},
		{
			MethodName: "PutCiphertext",
			Handler:    _Helium_PutCiphertext_Handler,
		},
		{
			MethodName: "EvalCircuit",
			Handler:    _Helium_EvalCircuit_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Register",
			Handler:       _Helium_Register_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "helium.proto",
}
